package project_Euler;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class P002_Even_Fibonacci_numbers {
	public static void main(String[] args) {
		int a=1;
		int b=2;
		int c=0;
		int sum=2;
				
		while(true){
			
			c=a+b;
			if(c>4000000){break;}
			
			a=b;
			b=c;
			if(c%2==0){sum+=c;}
			
			System.out.println(c);
		}
		System.out.println("피보나치 수열 값의 합: "+sum);
	}//main end
}//class end
